"""
BidForge AI — DOCX Exporter
===========================
Assembles a complete, professional proposal document using python-docx.

Structure:
1. Cover Page
2. Executive Summary (Generated by GROQ)
3. Proposal Narrative (from proposal_sections)
4. Compliance Checklist (from compliance_items)
5. Win Score Summary (from bid_scores)
"""

from __future__ import annotations

import logging
import os
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor
from fastapi import HTTPException, status
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_groq import ChatGroq

from app.services.capability_store import get_all_capabilities
from app.utils.supabase_client import get_supabase

logger = logging.getLogger(__name__)

GROQ_MODEL = "llama-3.3-70b-versatile"
COMPANY_NAME = "Pakistani IT Services & Engineering Company" # generic company name

_BIDFORGE_TMP = Path(tempfile.gettempdir()) / "bidforge"


def _get_workspace_dir(workspace_id: str) -> Path:
    d = _BIDFORGE_TMP / workspace_id
    d.mkdir(parents=True, exist_ok=True)
    return d


async def _generate_exec_summary(workspace_name: str, proposal_text: str) -> str:
    """Generate a 1-paragraph executive summary using GROQ."""
    api_key = os.getenv("GROQ_API_KEY", "")
    if not api_key:
        return "Executive summary could not be generated (GROQ_API_KEY missing)."
        
    llm = ChatGroq(model=GROQ_MODEL, temperature=0.7, max_tokens=300, api_key=api_key)
    
    prompt = f"""You are a professional bid writer.
Write a single, compelling 1-paragraph executive summary for a proposal titled: "{workspace_name}".
Base it loosely on these proposal snippets:
{proposal_text[:2000]}

Do not include greetings. Just write the paragraph."""

    from app.utils.llm_cache import cached_invoke, demo_fallback

    messages = [
        SystemMessage(content="You write compelling executive summaries for IT proposals."),
        HumanMessage(content=prompt),
    ]
    try:
        # Cache-first (Fix 10) — this was the one LLM call site left unwired,
        # which is why exports said "Executive summary generation failed."
        return await cached_invoke("exec_summary", llm, messages)
    except Exception as exc:
        logger.error("Failed to generate exec summary: %s", exc)
        fallback = demo_fallback("exec_summary", str(messages[-1].content))
        if fallback:
            return fallback
        # Degrade to a deterministic, honest summary instead of an error line
        return (
            f"This proposal for '{workspace_name}' presents our company's relevant "
            "past-project experience, certifications, and delivery approach against "
            "each requirement of the RFP, as detailed in the narrative sections below."
        )


def _add_cover_page(doc, workspace_name: str):
    doc.add_paragraph()
    doc.add_paragraph()
    
    title = doc.add_paragraph(workspace_name)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.size = Pt(28)
        run.bold = True
        run.font.color.rgb = RGBColor(0, 51, 102)

    doc.add_paragraph()
    
    subtitle = doc.add_paragraph("Technical & Commercial Proposal")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in subtitle.runs:
        run.font.size = Pt(18)
        
    doc.add_paragraph("\n\n\n\n\n\n")
    
    info = doc.add_paragraph()
    info.alignment = WD_ALIGN_PARAGRAPH.CENTER
    info.add_run(f"Submitted by: {COMPANY_NAME}\n").bold = True
    info.add_run(f"Date: {datetime.now().strftime('%d %B %Y')}\n")
    
    doc.add_paragraph("\n\n\n\n")
    footer = doc.add_paragraph("Prepared by BidForge AI")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in footer.runs:
        run.font.size = Pt(10)
        run.font.color.rgb = RGBColor(128, 128, 128)
        
    doc.add_page_break()


def _add_exec_summary(doc, summary_text: str):
    doc.add_heading("1. Executive Summary", level=1)
    doc.add_paragraph(summary_text)
    doc.add_page_break()


def _add_proposal_sections(doc, sections: list[dict], capabilities_map: dict):
    doc.add_heading("2. Proposal Narrative", level=1)
    
    # Natural sort ("2" before "10", letters after numbers, General last) —
    # plain string sort put Section 10 before Section 4.
    from app.services.proposal_generator import section_sort_key
    sections.sort(key=lambda x: section_sort_key(x.get("section_ref")))
    
    for sec in sections:
        title = sec.get("section_title") or f"Section {sec.get('section_ref', '')}"
        doc.add_heading(title, level=2)
        
        text = sec.get("edited_draft") or sec.get("ai_draft") or ""
        doc.add_paragraph(text)
        
        # Source line
        req_id = sec.get("requirement_id")
        if req_id in capabilities_map:
            cap_name = capabilities_map[req_id]
            p = doc.add_paragraph()
            run = p.add_run(f"Source: Derived from past experience in '{cap_name}'")
            run.font.size = Pt(9)
            run.font.italic = True
            run.font.color.rgb = RGBColor(100, 100, 100)


def _add_compliance_checklist(doc, compliance_items: list[dict], req_map: dict):
    doc.add_page_break()
    doc.add_heading("3. Compliance Checklist", level=1)
    
    table = doc.add_table(rows=1, cols=3)
    table.style = 'Light Shading Accent 1'
    
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Requirement'
    hdr_cells[1].text = 'Status'
    hdr_cells[2].text = 'Gap Note'
    
    for ci in compliance_items:
        req_id = ci.get("requirement_id")
        req_text = req_map.get(req_id, "Unknown Requirement")
        status = ci.get("status", "fail").lower()
        note = ci.get("gap_note") or ""
        
        row_cells = table.add_row().cells
        row_cells[0].text = req_text
        
        if status == "pass":
            row_cells[1].text = "✅ PASS"
        elif status == "partial":
            row_cells[1].text = "⚠️ PARTIAL"
        else:
            row_cells[1].text = "❌ FAIL"
            
        row_cells[2].text = note


def _add_win_score(doc, score: dict):
    doc.add_page_break()
    doc.add_heading("4. BidForge AI Win Score Analysis", level=1)
    
    overall = score.get("overall_score_pct", 0)
    decision = score.get("decision", "NO-GO")
    
    marker = "✅" if decision == "GO" else ("⚠️" if decision == "CONDITIONAL" else "❌")
    
    doc.add_paragraph(f"Overall Score: {overall}%\nDecision: {decision} {marker}", style='Intense Quote')
    
    bd = score.get("score_breakdown", {}).get("raw_scores", {})
    if bd:
        doc.add_heading("Score Breakdown", level=2)
        table = doc.add_table(rows=1, cols=2)
        table.style = 'Light List Accent 1'
        table.rows[0].cells[0].text = 'Criterion'
        table.rows[0].cells[1].text = 'Score'
        
        for k, v in bd.items():
            row_cells = table.add_row().cells
            row_cells[0].text = k.replace("_", " ").title()
            row_cells[1].text = f"{v*100:.1f}%"


async def generate_docx_export(workspace_id: str) -> str:
    """
    Generate the final DOCX proposal.
    Returns the absolute file path to the generated DOCX.
    """
    sb = get_supabase()
    
    # ── Load Data ────────────────────────────────────────────────────────────
    ws_res = sb.table("workspaces").select("name").eq("id", workspace_id).single().execute()
    if not ws_res.data:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Workspace not found")
    workspace_name = ws_res.data.get("name", "Proposal")
    
    sec_res = sb.table("proposal_sections").select("*").eq("workspace_id", workspace_id).execute()
    sections = sec_res.data or []
    
    req_res = sb.table("requirements").select("*").eq("workspace_id", workspace_id).execute()
    requirements = req_res.data or []
    req_map = {r["id"]: r.get("requirement", "") for r in requirements}
    
    comp_res = sb.table("compliance_items").select("*").eq("workspace_id", workspace_id).execute()
    compliance_items = comp_res.data or []
    
    # Canonical table is bid_scores (Fix 12); legacy fallback until renamed.
    try:
        score_res = sb.table("bid_scores").select("*").eq("workspace_id", workspace_id).execute()
    except Exception:
        score_res = sb.table("win_scores").select("*").eq("workspace_id", workspace_id).execute()
        logger.warning("Read score from LEGACY win_scores table — run: "
                       "ALTER TABLE win_scores RENAME TO bid_scores;")
    score = score_res.data[0] if score_res.data else {}
    
    caps = get_all_capabilities()
    cap_map = {c["id"]: c.get("project_title", "") for c in caps}
    
    # Map requirement -> matched capability project name
    req_to_cap_name = {}
    for ci in compliance_items:
        cap_id = ci.get("matched_capability_id")
        if cap_id and cap_id in cap_map:
            req_to_cap_name[ci["requirement_id"]] = cap_map[cap_id]
            
    # ── Exec Summary Gen ─────────────────────────────────────────────────────
    combined_draft = " ".join((s.get("edited_draft") or s.get("ai_draft") or "") for s in sections)
    exec_summary = await _generate_exec_summary(workspace_name, combined_draft)

    # ── Build Document ───────────────────────────────────────────────────────
    try:
        from docx import Document
    except ImportError:
        raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, "python-docx not installed")
        
    doc = Document()
    
    _add_cover_page(doc, workspace_name)
    _add_exec_summary(doc, exec_summary)
    _add_proposal_sections(doc, sections, req_to_cap_name)
    _add_compliance_checklist(doc, compliance_items, req_map)
    _add_win_score(doc, score)
    
    # ── Save Document ────────────────────────────────────────────────────────
    # Unique filename per export — a fixed name hits Windows file locks when
    # the previous copy is still open/being streamed, making re-export hang.
    save_dir = _get_workspace_dir(workspace_id)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    save_path = save_dir / f"proposal_draft_{stamp}.docx"

    doc.save(str(save_path))

    logger.info("Generated DOCX for workspace=%s at %s", workspace_id, save_path)
    return str(save_path)


# ═══════════════════════════════════════════════════════════════════════════
# FULL PROPOSAL EXPORT
# Complete 8-section proposal document:
#   1. Cover Page                    5. Company Profile & Credentials
#   2. Executive Summary             6. Relevant Past Projects (3 case studies)
#   3. Understanding of Requirements 7. Compliance Matrix
#   4. Technical Proposal            8. Appendices
# Uses approved/edited drafts where saved; flags gaps explicitly; never
# fabricates — every narrative is grounded in the capability library.
# ═══════════════════════════════════════════════════════════════════════════

async def _llm_text(tag: str, system: str, user: str, fallback_text: str,
                    max_tokens: int = 700) -> str:
    """One cached LLM call with provider rotation; degrades to fallback_text."""
    api_key = os.getenv("GROQ_API_KEY", "")
    if not api_key:
        return fallback_text

    from app.utils.llm_cache import cached_invoke, demo_fallback

    llm = ChatGroq(model=GROQ_MODEL, temperature=0.6, max_tokens=max_tokens, api_key=api_key)
    messages = [SystemMessage(content=system), HumanMessage(content=user)]
    try:
        return await cached_invoke(tag, llm, messages)
    except Exception as exc:
        logger.error("LLM call failed for full-proposal tag '%s': %s", tag, exc)
        fb = demo_fallback(tag, user)
        return fb or fallback_text


def _add_full_cover_page(doc, workspace_name: str):
    doc.add_paragraph()
    doc.add_paragraph()

    title = doc.add_paragraph(COMPANY_NAME)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.size = Pt(24)
        run.bold = True
        run.font.color.rgb = RGBColor(0, 51, 102)

    doc.add_paragraph()

    subtitle = doc.add_paragraph("Technical & Commercial Proposal")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in subtitle.runs:
        run.font.size = Pt(18)

    ref = doc.add_paragraph(f"RFP Reference: {workspace_name}")
    ref.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in ref.runs:
        run.font.size = Pt(13)
        run.font.italic = True

    doc.add_paragraph("\n\n\n\n\n\n")

    info = doc.add_paragraph()
    info.alignment = WD_ALIGN_PARAGRAPH.CENTER
    info.add_run(f"Submitted by: {COMPANY_NAME}\n").bold = True
    info.add_run(f"Date: {datetime.now().strftime('%d %B %Y')}\n")

    doc.add_paragraph("\n\n\n\n")
    footer = doc.add_paragraph("Prepared with BidForge AI")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in footer.runs:
        run.font.size = Pt(10)
        run.font.color.rgb = RGBColor(128, 128, 128)

    doc.add_page_break()


async def _understanding_text(workspace_name: str, requirements: list[dict]) -> str:
    """LLM-written 'Understanding of Requirements'; deterministic fallback."""
    by_type: dict[str, int] = {}
    for r in requirements:
        t = str(r.get("type") or "other")
        by_type[t] = by_type.get(t, 0) + 1
    type_summary = ", ".join(f"{v} {k}" for k, v in sorted(by_type.items()))

    fallback = (
        f"We have carefully reviewed the RFP '{workspace_name}', which comprises "
        f"{len(requirements)} extracted requirements ({type_summary}). Our response in "
        "the Technical Proposal section below addresses each mandatory requirement and "
        "question individually, citing evidence from our delivered-project record."
    )

    req_lines = "\n".join(
        f"- [{r.get('section_ref', 'General')}] {str(r.get('requirement', ''))[:200]}"
        for r in requirements[:40]
    )
    user = (
        f"RFP title: {workspace_name}\n"
        f"Total requirements extracted: {len(requirements)} ({type_summary})\n\n"
        f"Key requirements:\n{req_lines}\n\n"
        "Write the 'Understanding of Requirements' section of our proposal: 2-3 formal "
        "paragraphs showing the client we understood what they need — the project's purpose, "
        "scope, and critical success factors. Do NOT invent facts beyond the requirements "
        "listed. Do NOT add headings. Plain narrative text only."
    )
    return await _llm_text(
        "understanding_reqs",
        "You are a professional bid writer. You write formal, client-facing proposal prose. "
        "Never fabricate facts.",
        user, fallback,
    )


def _add_technical_proposal(doc, sections: list[dict], req_map: dict,
                            req_to_cap_name: dict,
                            ref_to_cap_names: dict | None = None):
    doc.add_heading("4. Technical Proposal", level=1)
    doc.add_paragraph(
        "Our response to each requirement of the RFP is set out below. Where our "
        "capability library provides direct evidence, the supporting project is cited; "
        "requirements without matching evidence are flagged explicitly."
    )

    from app.services.proposal_generator import section_sort_key
    sections = sorted(sections, key=lambda x: section_sort_key(x.get("section_ref")))

    for i, sec in enumerate(sections, start=1):
        title = sec.get("section_title") or f"Section {sec.get('section_ref', '')}"
        doc.add_heading(f"4.{i} {title}", level=2)

        req_id = sec.get("requirement_id")
        req_text = req_map.get(req_id)
        if req_text:
            p = doc.add_paragraph()
            run = p.add_run(f"Requirement: {req_text}")
            run.font.italic = True
            run.font.size = Pt(10)
            run.font.color.rgb = RGBColor(80, 80, 80)

        # Approved/edited text always wins over the raw AI draft.
        text = sec.get("edited_draft") or sec.get("ai_draft") or ""
        if text:
            doc.add_paragraph(text)

        cap_name = req_to_cap_name.get(req_id)
        if not cap_name and not req_id and ref_to_cap_names:
            # Legacy sections (saved before the requirement_id migration) can't
            # be joined 1:1 — cite the matched evidence for the whole RFP
            # section group instead of falsely flagging every one as a gap.
            group = ref_to_cap_names.get(str(sec.get("section_ref") or ""))
            if group:
                cap_name = ", ".join(group[:3])

        if cap_name:
            p = doc.add_paragraph()
            run = p.add_run(f"Supporting evidence: '{cap_name}' (capability library)")
            run.font.size = Pt(9)
            run.font.italic = True
            run.font.color.rgb = RGBColor(100, 100, 100)
        else:
            p = doc.add_paragraph()
            run = p.add_run("[GAP FLAGGED - No evidence found for this requirement]")
            run.bold = True
            run.font.color.rgb = RGBColor(192, 0, 0)


def _add_company_profile(doc, caps: list[dict]):
    """Deterministic profile aggregated from the capability library — no LLM,
    so nothing can be fabricated."""
    doc.add_heading("5. Company Profile & Credentials", level=1)

    domains = sorted({c.get("domain", "") for c in caps if c.get("domain")})
    certs = sorted({c.get("certification") for c in caps if c.get("certification")})
    years = [int(c["year_completed"]) for c in caps
             if str(c.get("year_completed") or "").isdigit()]
    client_types = sorted({c.get("client_type", "") for c in caps if c.get("client_type")})

    doc.add_paragraph(
        f"{COMPANY_NAME} has successfully delivered {len(caps)} documented projects"
        + (f" between {min(years)} and {max(years)}" if years else "")
        + f" across {len(domains)} practice areas, serving "
        + ", ".join(client_types).lower() + " clients."
    )

    doc.add_heading("Practice Areas", level=2)
    for d in domains:
        doc.add_paragraph(d, style="List Bullet")

    if certs:
        doc.add_heading("Certifications & Standards", level=2)
        for c in certs:
            doc.add_paragraph(c, style="List Bullet")


def _pick_top_projects(caps: list[dict], compliance_items: list[dict],
                       n: int = 3) -> list[dict]:
    """The n capabilities most frequently matched against this RFP's
    requirements; pad with the most recent projects if fewer were matched."""
    counts: dict[str, int] = {}
    for ci in compliance_items:
        cap_id = ci.get("matched_capability_id")
        if cap_id:
            counts[cap_id] = counts.get(cap_id, 0) + 1

    by_id = {c.get("id"): c for c in caps}
    picked = [by_id[cid] for cid, _ in
              sorted(counts.items(), key=lambda kv: -kv[1]) if cid in by_id][:n]

    if len(picked) < n:
        picked_ids = {c.get("id") for c in picked}
        rest = sorted(
            (c for c in caps if c.get("id") not in picked_ids),
            key=lambda c: -(int(c["year_completed"])
                            if str(c.get("year_completed") or "").isdigit() else 0),
        )
        picked.extend(rest[: n - len(picked)])
    return picked


async def _add_past_projects(doc, projects: list[dict]):
    doc.add_heading("6. Relevant Past Projects", level=1)

    for proj in projects:
        title = proj.get("project_title", "Untitled Project")
        doc.add_heading(title, level=2)

        meta = doc.add_paragraph()
        run = meta.add_run(
            f"Domain: {proj.get('domain', 'N/A')}  |  "
            f"Client: {proj.get('client_type', 'N/A')}  |  "
            f"Value: {proj.get('contract_value', 'N/A')}  |  "
            f"Completed: {proj.get('year_completed', 'N/A')}"
            + (f"  |  Certification: {proj['certification']}"
               if proj.get("certification") else "")
        )
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(100, 100, 100)

        fallback = str(proj.get("summary", ""))
        user = (
            f"Project record (the ONLY source of truth — do not add facts):\n"
            f"Title: {title}\nDomain: {proj.get('domain')}\n"
            f"Summary: {proj.get('summary')}\n"
            f"Client type: {proj.get('client_type')}\n"
            f"Contract value: {proj.get('contract_value')}\n"
            f"Duration: {proj.get('duration_months')} months\n"
            f"Completed: {proj.get('year_completed')}\n"
            f"Certification: {proj.get('certification') or 'None'}\n\n"
            "Write a short case study (one paragraph, 4-6 sentences) for a proposal: "
            "the challenge, what we delivered, and the measurable outcome. Formal tone. "
            "Use ONLY the facts above. No headings."
        )
        text = await _llm_text(
            "case_study",
            "You are a professional bid writer. You write concise project case studies "
            "strictly from the facts provided. Never fabricate.",
            user, fallback, max_tokens=400,
        )
        doc.add_paragraph(text)


def _add_compliance_matrix(doc, compliance_items: list[dict], req_map: dict,
                           cap_map: dict):
    doc.add_page_break()
    doc.add_heading("7. Compliance Matrix", level=1)

    table = doc.add_table(rows=1, cols=3)
    table.style = "Light Shading Accent 1"
    hdr = table.rows[0].cells
    hdr[0].text = "Requirement"
    hdr[1].text = "Compliant"
    hdr[2].text = "Evidence"

    for ci in compliance_items:
        req_text = req_map.get(ci.get("requirement_id"), "Unknown Requirement")
        st = str(ci.get("status", "fail")).lower()
        cap_title = cap_map.get(ci.get("matched_capability_id") or "")

        row = table.add_row().cells
        row[0].text = req_text
        row[1].text = "Yes" if st == "pass" else ("Partial" if st == "partial" else "No")
        row[2].text = (
            cap_title or ci.get("gap_note")
            or "[GAP FLAGGED - No evidence found for this requirement]"
        )


def _add_appendices(doc):
    doc.add_page_break()
    doc.add_heading("8. Appendices", level=1)
    for item in (
        "Appendix A — Company registration & legal documents (to be attached)",
        "Appendix B — Certification copies (to be attached)",
        "Appendix C — Detailed CVs of key personnel (to be attached)",
        "Appendix D — Financial statements (to be attached)",
    ):
        doc.add_paragraph(item, style="List Bullet")


async def generate_full_proposal_docx(workspace_id: str) -> str:
    """
    Generate the complete 8-section proposal document.
    Returns the absolute file path to the generated DOCX.
    """
    sb = get_supabase()

    ws_res = sb.table("workspaces").select("name").eq("id", workspace_id).single().execute()
    if not ws_res.data:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Workspace not found")
    workspace_name = ws_res.data.get("name", "Proposal")

    sections = (sb.table("proposal_sections").select("*")
                .eq("workspace_id", workspace_id).execute()).data or []
    requirements = (sb.table("requirements").select("*")
                    .eq("workspace_id", workspace_id).execute()).data or []
    req_map = {r["id"]: r.get("requirement", "") for r in requirements}
    compliance_items = (sb.table("compliance_items").select("*")
                        .eq("workspace_id", workspace_id).execute()).data or []

    if not sections:
        raise HTTPException(
            status.HTTP_422_UNPROCESSABLE_ENTITY,
            "No proposal sections found — generate the proposal draft first.",
        )

    caps = get_all_capabilities()
    cap_map = {c["id"]: c.get("project_title", "") for c in caps}
    req_to_cap_name = {
        ci["requirement_id"]: cap_map[ci["matched_capability_id"]]
        for ci in compliance_items
        if ci.get("matched_capability_id") in cap_map
    }

    # Evidence grouped by RFP section ref — fallback for legacy proposal
    # sections that were saved without a requirement_id.
    req_ref_of = {r["id"]: str(r.get("section_ref") or "") for r in requirements}
    ref_to_cap_names: dict[str, list[str]] = {}
    for req_id, cap_name in req_to_cap_name.items():
        ref = req_ref_of.get(req_id)
        if ref and cap_name not in ref_to_cap_names.setdefault(ref, []):
            ref_to_cap_names[ref].append(cap_name)

    # Narrative pieces (LLM, cached, provider-rotated; deterministic fallback)
    combined_draft = " ".join(
        (s.get("edited_draft") or s.get("ai_draft") or "") for s in sections
    )
    exec_summary = await _generate_exec_summary(workspace_name, combined_draft)
    understanding = await _understanding_text(workspace_name, requirements)
    top_projects = _pick_top_projects(caps, compliance_items, n=3)

    # ── Build Document ───────────────────────────────────────────────────────
    doc = Document()

    _add_full_cover_page(doc, workspace_name)

    doc.add_heading("2. Executive Summary", level=1)
    doc.add_paragraph(exec_summary)
    doc.add_page_break()

    doc.add_heading("3. Understanding of Requirements", level=1)
    doc.add_paragraph(understanding)
    doc.add_page_break()

    _add_technical_proposal(doc, sections, req_map, req_to_cap_name, ref_to_cap_names)
    doc.add_page_break()

    _add_company_profile(doc, caps)
    doc.add_page_break()

    await _add_past_projects(doc, top_projects)
    _add_compliance_matrix(doc, compliance_items, req_map, cap_map)
    _add_appendices(doc)

    # ── Save ─────────────────────────────────────────────────────────────────
    save_dir = _get_workspace_dir(workspace_id)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    save_path = save_dir / f"full_proposal_{stamp}.docx"
    doc.save(str(save_path))

    logger.info("Generated FULL proposal DOCX for workspace=%s at %s",
                workspace_id, save_path)
    return str(save_path)
